services:
    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: db-ticketing-system
        ports:
            - 3306:3306
    phpmyadmin:
        image: phpmyadmin
        ports:
            - 8081:80
        environment:
            PMA_HOST: mysql
